"use client";

import { motion } from "framer-motion";
import {
    BrainCircuit,
    FileText,
    BarChart3,
    Building2,
    ArrowRight,
    Sparkles,
} from "lucide-react";

const features = [
    {
        icon: BrainCircuit,
        title: "AI Mock Interviews",
        description:
            "Practice realistic technical and HR interviews generated by Gemini AI with intelligent follow-up questions.",
        gradient: "from-indigo-500 to-violet-500",
    },
    {
        icon: FileText,
        title: "Resume-Based Questions",
        description:
            "Upload your resume and receive personalized interview questions tailored to your skills and experience.",
        gradient: "from-cyan-500 to-blue-500",
    },
    {
        icon: BarChart3,
        title: "Detailed Performance Reports",
        description:
            "Get instant AI feedback, scoring, strengths, weaknesses, and actionable recommendations after every interview.",
        gradient: "from-emerald-500 to-green-500",
    },
    {
        icon: Building2,
        title: "Company Specific",
        description:
            "Prepare for interviews from Google, Microsoft, Amazon, Infosys, TCS, Deloitte, Accenture, and more.",
        gradient: "from-pink-500 to-orange-500",
    },
];

export default function Features() {
    return (
        <section
            id="features"
            className="relative bg-slate-950 py-28"
        >
            {/* Background Glow */}
            <div className="absolute left-0 top-32 h-80 w-80 rounded-full bg-indigo-600/10 blur-[120px]" />
            <div className="absolute right-0 bottom-20 h-80 w-80 rounded-full bg-violet-600/10 blur-[120px]" />

            <div className="relative mx-auto max-w-7xl px-6">

                {/* Heading */}
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6 }}
                    className="mx-auto mb-20 max-w-3xl text-center"
                >
                    <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-2 text-sm text-indigo-300">
                        <Sparkles className="h-4 w-4" />
                        Powerful Features
                    </div>

                    <h2 className="text-5xl font-black text-white">
                        Everything You Need
                        <span className="bg-gradient-to-r from-indigo-400 via-violet-400 to-cyan-400 bg-clip-text text-transparent">
                            {" "}
                            To Crack Interviews
                        </span>
                    </h2>

                    <p className="mt-6 text-lg leading-8 text-slate-400">
                        MockMate combines AI, analytics, and company-specific preparation
                        to help you become interview-ready faster than ever.
                    </p>
                </motion.div>

                {/* Cards */}
                <div className="grid gap-8 md:grid-cols-2">
                    {features.map((feature, index) => {
                        const Icon = feature.icon;

                        return (
                            <motion.div
                                key={feature.title}
                                initial={{ opacity: 0, y: 40 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{
                                    delay: index * 0.15,
                                    duration: 0.5,
                                }}
                                className="group relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-8 backdrop-blur-xl transition-all duration-500 hover:-translate-y-3 hover:border-indigo-500/40"
                            >
                                {/* Glow */}
                                <div className="absolute inset-0 opacity-0 transition duration-500 group-hover:opacity-100">
                                    <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-indigo-500/20 blur-3xl" />
                                </div>

                                <div
                                    className={`mb-8 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${feature.gradient}`}
                                >
                                    <Icon className="h-8 w-8 text-white" />
                                </div>

                                <h3 className="text-2xl font-bold text-white">
                                    {feature.title}
                                </h3>

                                <p className="mt-5 leading-8 text-slate-400">
                                    {feature.description}
                                </p>

                                <button className="mt-8 inline-flex items-center gap-2 font-semibold text-indigo-400 transition group-hover:gap-3">
                                    Learn More
                                    <ArrowRight className="h-5 w-5" />
                                </button>
                            </motion.div>
                        );
                    })}
                </div>

            </div>
        </section>
    );
}